name: Publish zip

on:
  release:
    types: [published]

jobs:
  publish-zip:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Paso 1: Checkout del repositorio completo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: master
          fetch-depth: 0

      # Paso 2: Obtener la versión del release recién publicado
      - name: Get release version
        id: release-version
        run: |
          version="${GITHUB_REF#refs/tags/v}"
          echo "Release version: $version"
          echo "version=$version" >> $GITHUB_OUTPUT

      # Paso 3: Actualizar hacs.json con la última versión de Home Assistant
      - name: Get latest Home Assistant version
        id: ha-version
        run: |
          latest=$(curl -s https://api.github.com/repos/home-assistant/core/releases/latest | jq -r .tag_name)
          latest_clean=${latest#v}
          echo "ha_version=$latest_clean" >> $GITHUB_OUTPUT

      - name: Update hacs.json
        run: |
          ha_version="${{ steps.ha-version.outputs.ha_version }}"
          jq --arg ver "$ha_version" '.homeassistant = $ver' hacs.json > tmp.json && mv tmp.json hacs.json

      - name: Commit updated hacs.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add hacs.json
          if git commit -m "chore: update hacs.json with latest Home Assistant version [skip ci]"; then
            git push origin master
          else
            echo "No changes to commit"
          fi

      # Paso 4: Crear zip de la integración con nombre fijo meteocat.zip
      - name: Zip integration
        run: |
          cd custom_components/meteocat
          zip -r "$GITHUB_WORKSPACE/meteocat.zip" ./
          echo "Zip created at $GITHUB_WORKSPACE/meteocat.zip"

      # Paso 5: Subir meteocat.zip al release de GitHub
      - name: Upload meteocat.zip to release
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: meteocat.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
