name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Configurar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 2: Configurar Node.js (requerido para semantic-release)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Asegúrate de usar una versión compatible con semantic-release

      # Paso 3: Instalar dependencias necesarias
      - name: Install dependencies
        run: npm ci

      # Paso 4: Ejecutar semantic-release
      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Token automático para crear releases en GitHub
        run: npx semantic-release
