name: Sync to GitLab

on:
  push:
    branches:
      - master
  create:
    tags:
      - 'v*'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "github-bot"
          git config user.email "bot@github.com"

      - name: Push to GitLab mirror
        env:
          GL_REMOTE_URL: ${{ secrets.GL_REMOTE_URL }}
          GL_TOKEN: ${{ secrets.GL_TOKEN }}
        run: |
          # Añadimos el remoto GitLab con autenticación por token
          git remote add gitlab "https://oauth2:${GL_TOKEN}@${GL_REMOTE_URL#https://}"

          # Forzamos sincronización completa (commits, tags, ramas)
          git push --mirror gitlab
